language: cpp
dist: trusty

os: 
  - linux
  - osx

compiler:
  - g++
  - clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - cd .. && rm -r ./build

